# Generated by Django 3.0.7 on 2020-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaveplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveplan',
            name='approval_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AD', 'Approved'), ('RD', 'Rejected')], default='PD', max_length=2),
        ),
    ]
