# Generated by Django 3.1.5 on 2021-02-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20201002_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='balance',
        ),
    ]
