# Generated by Django 3.1.5 on 2021-02-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_remove_leaverecord_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveplan',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='leaveplan',
            name='plan_date',
            field=models.DateField(auto_now=True),
        ),
    ]
