# Generated by Django 3.1.5 on 2021-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20210222_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='apply_date',
            field=models.DateField(auto_now=True),
        ),
    ]
