# Generated by Django 3.1.5 on 2021-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20210222_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveplan',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
