# Generated by Django 3.1.5 on 2021-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_leaveplan_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=8),
        ),
    ]
