# Generated by Django 3.1.5 on 2021-02-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_leaveapplication_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
    ]
