# Generated by Django 3.0.7 on 2020-09-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='name',
        ),
        migrations.AddField(
            model_name='deduction',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deduction',
            name='sacco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deduction',
            name='salary_advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
