# Generated by Django 3.0.7 on 2020-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200908_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='police_fine',
            field=models.IntegerField(default=0),
        ),
    ]
