# Generated by Django 3.0.7 on 2020-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_statutorydeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='local_service_tax',
            field=models.FloatField(default=0),
        ),
    ]
