# Generated by Django 3.0.7 on 2020-10-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20201013_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutorydeduction',
            name='local_service_tax',
            field=models.FloatField(default=0),
        ),
    ]
