# Generated by Django 3.0.7 on 2020-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20201013_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutorydeduction',
            name='local_service_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
