# Generated by Django 3.0.7 on 2020-10-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20201013_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutorydeduction',
            name='local_service_tax',
            field=models.FloatField(),
        ),
    ]
