# Generated by Django 3.0.7 on 2020-08-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_offence_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
