# Generated by Django 3.0.7 on 2020-08-03 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_offence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
