# Generated by Django 3.0.7 on 2020-08-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_bonus'),
        ('contracts', '0005_offence_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('termination_letter', models.FileField(upload_to='termination_letters')),
                ('clearance_form', models.FileField(upload_to='termination_forms')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
