# Generated by Django 3.0.7 on 2020-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_termination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termination',
            name='clearance_form',
            field=models.FileField(blank=True, upload_to='termination_forms'),
        ),
        migrations.AlterField(
            model_name='termination',
            name='termination_letter',
            field=models.FileField(blank=True, upload_to='termination_letters'),
        ),
    ]
