# Generated by Django 3.1.5 on 2021-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeapplication',
            name='Expiry',
            field=models.BooleanField(default=False),
        ),
    ]
