# Generated by Django 3.1.5 on 2021-02-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_overtimeapplication_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimeapplication',
            old_name='Expiry',
            new_name='expired',
        ),
    ]
