# Generated by Django 3.1.5 on 2021-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_testcronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcronjob',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
