# Generated by Django 3.1.5 on 2021-02-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_testcronjob_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
    ]
