# Generated by Django 3.0.7 on 2020-08-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentkpi',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='departmentkpi',
            old_name='out_of_score',
            new_name='weight',
        ),
    ]
