# Generated by Django 3.0.7 on 2020-08-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20200817_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentkpi',
            name='description',
            field=models.TextField(),
        ),
    ]
