# Generated by Django 3.0.7 on 2020-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20200817_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeekpi',
            old_name='out_of_score',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='employeekpi',
            name='name',
        ),
        migrations.AddField(
            model_name='employeekpi',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
