# Generated by Django 3.0.7 on 2020-08-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_bonus'),
        ('performance', '0005_employeekpi_assessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeekpi',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
