# Generated by Django 3.0.7 on 2020-08-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20200819_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentkpi',
            old_name='description',
            new_name='measure_of_success',
        ),
        migrations.RenameField(
            model_name='employeekpi',
            old_name='description',
            new_name='measure_of_success',
        ),
    ]
