# Generated by Django 3.1.5 on 2021-03-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='media/csvs/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nssf', models.FloatField()),
                ('employer_nssf', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('paye', models.FloatField()),
                ('total_nssf_contrib', models.FloatField(default=0)),
                ('overtime', models.FloatField()),
                ('bonus', models.FloatField(default=0)),
                ('local_service_tax', models.FloatField()),
                ('local_service_tax_deduction', models.FloatField()),
                ('sacco_deduction', models.FloatField()),
                ('damage_deduction', models.FloatField()),
                ('salary_advance', models.FloatField()),
                ('police_fine', models.FloatField()),
                ('prorate', models.CharField(default='0.0', max_length=20)),
                ('basic_salary', models.IntegerField(default=0)),
                ('currency_rate', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='settings.currency')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('payroll_record', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrecord')),
            ],
        ),
    ]
