# Generated by Django 3.0.7 on 2020-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='currency_rate',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basic_salary',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
