# Generated by Django 3.0.7 on 2020-08-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20200729_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='basic_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='currency_rate',
            field=models.IntegerField(default=0),
        ),
    ]
