# Generated by Django 3.0.7 on 2020-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20200802_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
