# Generated by Django 3.0.7 on 2020-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20200802_0246'),
        ('payroll', '0004_auto_20200730_1231'),
    ]

    operations = [
    ]
