# Generated by Django 3.0.7 on 2020-08-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollrecord_archived'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('year', 'month')},
        ),
    ]
