# Generated by Django 3.0.7 on 2020-08-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_merge_20200811_1145'),
        ('payroll', '0006_auto_20200828_1021'),
    ]

    operations = [
    ]
