# Generated by Django 3.0.7 on 2020-09-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20200828_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='police_fine',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_advance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
