# Generated by Django 3.0.7 on 2020-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20200908_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='local_service_tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='local_service_tax_deduction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
