# Generated by Django 3.0.7 on 2020-09-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_merge_20200828_1622'),
        ('payroll', '0007_auto_20200908_1345'),
    ]

    operations = [
    ]
