# Generated by Django 3.0.7 on 2020-09-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_merge_20200925_1351'),
        ('payroll', '0008_auto_20200928_1047'),
    ]

    operations = [
    ]
