# Generated by Django 3.0.7 on 2020-10-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_merge_20200928_1114'),
        ('payroll', '0009_csv'),
    ]

    operations = [
    ]
