# Generated by Django 3.0.7 on 2020-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
