# Generated by Django 3.0.7 on 2020-07-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_auto_20200703_0952'),
        ('organisation_details', '0004_auto_20200715_1439'),
    ]

    operations = [
    ]
